site_name: pybase-explainer
site_url: 
site_description: A python repo base 
repo_url: 
repo_name: pybase

nav:
  - Home: index.md 
  - Template: template.md
  - Python Packages:
    - Ruff: python/ruff.md
    - Deptry: python/deptry.md
    - Mkdocs: python/mkdocs.md
    - Pdm: python/pdm.md
    - Pytest: python/pytest.md
    - Pythonproject: python/pythonproject.md
    - Ty: python/ty.md
    - Uv: python/uv.md
    - Venv: python/venv.md
  - CI/CD:
    - Git: ci/git.md
    - Githubaction: ci/githubaction.md
    - Precommithook: ci/precommithook.md
  - IDEs:
    - Cursor: ide/cursor.md
    - Visualstudio: ide/visualstudio.md
  - Terminal:
    - Terminal: terminal/terminal.md
    - Ohmyposh: terminal/ohmyposh.md
    - Ssh: terminal/ssh.md

theme:
  name: material # Or 'readthedocs', 'mkdocs'
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: blue
      accent: light blue
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - toc.integrate
    


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - include-markdown
     

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

